services:
  test:
    image: darkzero1234/torchserve-resnet-densenet:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure