version: '3.8'

services:
  resnet:
    image: darkzero1234/torchserve-resnet-densenet:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == two
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  densenet:
    image: darkzero1234/torchserve-resnet-densenet:latest
    ports:
      - "8082:8080"
      - "8083:8081"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == three
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure